package com.ilhamshodiq.androidpemulasubmission;

import java.util.ArrayList;
import java.util.Locale;

public class ContentsData {
    private static String[] contentsName = {
            "Anti-Mage",
            "Arc Warden",
            "Bloodseeker",
            "Bounty Hunter",
            "Broodmother",
            "Clinkz",
            "Drow Ranger",
            "Ember Spirit",
            "Faceless Void",
            "Gyrocopter",
            "Hoodwink",
            "Juggernaut",
            "Lone Druid",
            "Luna",
            "Medusa",
            "Meepo",
            "Mirana",
            "Monkey King",
            "Morphling",
            "Naga Siren",
            "Nyx Assassin",
            "Pangolier",
            "Phantom Assassin",
            "Phantom Lancer",
            "Razor",
            "Riki",
            "Shadow Fiend",
            "slark",
            "Sniper",
            "Spectre",
            "Templar Assassin",
            "Terrorblade",
            "Troll Warlord",
            "Ursa",
            "Vengeful Spirit",
            "Venomancer",
            "Viper",
            "Weaver"
    };
    private static String[] contentType = {
            "Melee",
            "Ranged",
            "Melee",
            "Melee",
            "Melee",
            "Ranged",
            "Ranged",
            "Melee",
            "Melee",
            "Ranged",
            "Ranged",
            "Melee",
            "Ranged & Melee(Bear)",
            "Ranged",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Melee",
            "Melee",
            "Melee",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Melee",
            "Ranged",
            "Ranged",
            "Ranged",
            "Ranged"
    };

    private static String[] contentComplexity = {
            "★☆☆",
            "★★★",
            "★☆☆",
            "★☆☆",
            "★★☆",
            "★★☆",
            "★☆☆",
            "★★☆",
            "★★☆",
            "★☆☆",
            "★★☆",
            "★☆☆",
            "★★★",
            "★☆☆",
            "★☆☆",
            "★★★",
            "★★☆",
            "★★☆",
            "★★★",
            "★★☆",
            "★★☆",
            "★★☆",
            "★☆☆",
            "★★☆",
            "★☆☆",
            "★☆☆",
            "★★☆",
            "★★☆",
            "★☆☆",
            "★★☆",
            "★★☆",
            "★★☆",
            "★★☆",
            "★☆☆",
            "★☆☆",
            "★☆☆",
            "★☆☆",
            "★★☆"

    };

    private static String[] contentDetails = {
            "Di antara para bhikkhu pertapa Turstarkuri, hanya seorang pembantu muda yang cukup beruntung untuk lolos dari serangan legiun yang gugur di biara. Sekarang, bersumpah untuk menghilangkan tidak hanya sihir Dewa Mati, Anti-Mage kembali untuk membasmi sihir sama sekali. Dengan fokus belaka, dia Menghitung Mantra yang dilemparkan ke arahnya, mengembalikannya ke pengirimnya. Tidak ada trik penyihir yang cukup untuk menahan atau menghindari Anti-Mage, saat ia berkedip keluar dari jebakan apa pun, sementara pada saat yang sama mampu mengirim Fragmen dirinya untuk mengejar target di retrun. Dengan setiap ayunan pedangnya yang tidak biasa, Anti-Mage melangkah lebih dekat ke tujuannya untuk menghapus semua sihir, Menghancurkan Mana , menyiapkan kastor yang habis untuk binasa dalam Mana Void yang menghancurkan..",
            "Membuat salinan dirinya untuk split push.Sebuah fragmen pecahan dari kekuatan primordial yang sama dengan Ancients sendiri, Zet berusaha untuk mengakhiri ketidakharmonisan di antara faksi-faksi yang bertikai melalui cara apa pun yang diperlukan. Musuh soliter dilemparkan ke dalam keadaan Flux yang bergejolak , merobek kesehatan mereka dari waktu ke waktu. Mendistorsi ruang untuk menghasilkan Lapangan Pelindung yang melindungi sekutu, menghindari dan menyerang dengan efisiensi yang lebih besar. Zet memanggil Fragmen Spark dari dirinya sebelumnya yang berputar di tempat, dan mencari musuh terdekat. Apakah ada satu Arc Warden, atau dua? Berbekal item dan kemampuan asli, Self's Tempest Double menggandakan setiap mantra dan setiap serangan, membawa kekacauan dua kali lipat ke pertarungan apa pun.",
            "Permintaan darah si Kembar Flayed hanya bisa dipenuhi melalui pembantaian terus-menerus, tugas yang lebih cocok untuk Strygwyr. Didorong oleh Haus yang tak pernah terpuaskan , Bloodseeker merasakan darah orang yang terluka parah dari jarak bermil-mil jauhnya, dan mengejar mereka dengan kecepatan tinggi. Melalui tanda suci pada perlengkapannya, darah yang baru dikorbankan mengalir langsung ke Flayed Ones, menyisakan cukup untuk menyembuhkan lukanya dan memicu Kemarahannya . Strygwyr melukis tanah dengan cincin merah, membungkam musuh yang terperangkap dalam Ritual Darah ini . Memaksakan keputusan sulit pada musuhnya, bagi mereka yang berlari hanya mempercepat kematiannya sendiri. Pencari Darah Pecahsetiap arteri, menyebabkan korbannya mengalami pendarahan di setiap langkah. Untuk memenuhi tuntutan si Kembar Flayed, Bloodseeker bahkan mengorbankan sebagian miliknya, menyemprotkan darahnya sendiri di sekelilingnya dalam Kabut Berdarah . Dengan kehilangan darah atau oleh pedang suku Strygwyr, kematian hanyalah kesimpulan yang sudah pasti.",
            "Ketakutan adalah ibu dari rumor, dan cerita tentang asal usul Gondar hanyalah desas-desus. Untuk harga yang tepat, Pemburu Hadiah akan Melacak target mana pun untuk mengirimkan kepala mereka dan mengumpulkan hadiah mereka. Dia Berjalan menembus Bayangan ke dalam penjagaan terbaik, melumpuhkan targetnya dengan serangan mendadak, dan mencuri sebagian kekayaan mereka dengan serangan yang diperhitungkan . Bahkan target pada jarak yang lebih jauh tidak aman dari Bounty Hunter, karena Shurikennya yang tepercaya tampaknya memiliki pikirannya sendiri, mencari dan menyerang semua target yang dilacak oleh Bounty Hunter. Karena pada akhirnya, ini semua tentang emas.",
            "Menghuni tabung lava di bawah kaldera Gunung Pyrotheos , Arachnia Hitam bosan dengan petualang baru-baru ini yang menginjak banyak keturunannya. Maka, Ibu Pertiwi berangkat untuk menyingkirkan dunia dari setiap penyusup potensial, satu pahlawan pada satu waktu. Tubuh yang hangat membuat pembibitan yang ideal, fakta yang tidak hilang di Black Arachnia saat dia menyuntikkan telurnya ke musuh yang sekarat ke Spawn Spiderlings . Di sebidang tanah dia Memutar Jaring Serat Sutra , melindungi dirinya di dalam untuk memulihkan luka atau meletakkan Jerat untuk menangkap mangsanya. Didorong oleh Kelaparan yang Tak Terpuaskan, Ibu Induk menjadi hiruk-pikuk makan, menyedot cairan vital dari pahlawan yang berkeliaran dengan setiap gigitan, mengisi kembali dirinya untuk siklus spawn berikutnya.",
            "Saat Clinkz melepaskan panah terakhirnya, iblis Maraxiform menyulut tanah dengan api neraka, membakarnya sampai ke tulang. Namun, pemanah heroik itu tidak mati. Dia telah membunuh iblis, dan tanpa disadari mendapatkan hadiah raja-penyihir Sutherex — Kehidupan abadi. Diabadikan di jurang kematian, Clinkz sekarang memanfaatkan tubuh kerangkanya secara menguntungkan. Disamarkan , dia berjalan ke tanah yang tidak bersahabat, membentuk Pakta Kematian dengan satwa liar untuk mempelajari cara mereka dan memberdayakan tembakan dan vitalitasnya. Neraka iblis membakar di dalam tulang rusuknya, yang dengannya dia sekarang menghujani musuh-musuhnya dengan Api Kematian , Membakar Panahnya dengan efek yang menghancurkan. Saat cadangan diperlukan, Clinkz memanggil Tentara Pembakaran rekan senegaranya, membakar musuhnya dalam nyala api rentetan api neraka mereka.",
            "Tinggal jauh di dalam hutan, hanya sedikit yang pernah melihat sekilas Drow Ranger yang soliter dan sangat cantik. Kehadirannya hanya diketahui dari dinginnya Frost Arrows , menusuk jauh ke dalam hati musuhnya. Dinamakan dan dibesarkan oleh Drow yang simpatik , Traxex memanfaatkan warisannya untuk mengirimkan Gust yang kuat , membungkam dan memukul mundur penyerang yang berani terlalu dekat. Meskipun biasanya bertujuan untuk presisi, Traxex tidak menghindar dari metode yang tidak lazim, meluncurkan salvo cepat panah berujung es ke beberapa target sekaligus. Mengasah keterampilannya hingga presisi tiada tara, keahlian menembak legendaris Drow Ranger hanya meningkat dengan setiap pertempuran kecil yang lewat.",
            "Terkesan oleh ajaran Xin, Pembakaran Surgawi menghembuskan kehidupan ke dalam abu penyair-pejuang, dan dari sana gambar Xin muncul, terlahir kembali sebagai Roh Ember. Cepat dan sulit dipahami, guru hebat itu berlari melewati lawan-lawannya, menyerang setiap musuh sekali dengan Sleight of Fist sebelum kembali ke tempat asalnya. Dia melumpuhkan musuh dengan Searing Chains , menahan mereka di tempat melawan panas terik dari Flame Guard -nya . Di seberang negeri, rupa Xin yang bersinar berjaga-jaga. Roh Ember tiba di Sisa Apinya dari jarak yang tidak mungkin, menangkap yang tidak siap dalam semburan api sebelum mereka menyerahkan hidup mereka kepada pedang Xin yang terbakar.",
            "Darkteror adalah makhluk yang hukum ruang-waktunya tidak berlaku. Dia maju dan mundur dengan cepat melalui ruang, Waktu Berjalan melewati rintangan, memanipulasinya untuk menghindari kerusakan yang terjadi dan Menjeda musuhnya di tempat sejenak. Musuh di dekatnya merasakan kehadiran gravitasinya dan mengalami Time Dilation , memperlambat tidak hanya gerakan mereka, tetapi juga kecepatan mantra yang bisa dilemparkan. Dia merobek celah, membuat semua kecuali dirinya terhenti total. Beku dalam Waktu , musuh hanya bisa tidak menyadari saat Void Tanpa Wajah membongkar mereka dari dalam.",
            "Perangkat terbang non-magis pertama di dunia membutuhkan waktu lebih dari satu dekade untuk dibuat, dan kurang dari beberapa detik untuk ditembak jatuh. Tapi pilotnya tidak terhalang. Aurel kembali ke langit dengan Gyrocopter yang lebih baru dan lebih baik. Berbekal Flak Cannons , Gyrocopter dapat menyerang saat bepergian dan merobohkan seluruh bidang musuh bahkan pada jarak yang lebih jauh dari jangkauan senjata utama. Terhadap target yang berhasil lolos dari jangkauan meriam, alat ini dilengkapi dengan Rudal Pelacak yang dapat mengatur diri sendiri yang dapat membuntuti target mereka ke ujung dunia jika tidak ditembak jatuh. Dengan menjentikkan satu tombol, Rentetan Roket yang tampaknya tak berujung dapat dilepaskan pada siapa pun yang melangkah terlalu dekat dengan mesin terbang. Sebagai Keendia, Aurel pergi ke laut dan memasang dua peluncur roket besar di belakang konstruksi yang dimuat dengan peringatan, memungkinkan dia untuk Call Down serangan udara untuk menghancurkan seluruh sektor.",
            "Selalu siap ketika masalah terjadi Hoodwink hidup untuk menghadapi ancaman yang memenuhi hutan angker yang dia adopsi sebagai rumahnya. Seorang Penembak jitu alami yang membawa panah besar dan menembakkan Acorn Shots sementara masih bisa Berlari melintasi hutan dengan sangat mudah, Hoodwink hampir tidak mungkin untuk mengawasi dalam pertempuran dan Bushwhacks musuh-musuhnya ketika mereka tidak mengharapkannya. Kehilangan jejaknya sekali, dia akan menggunakan kesempatan untuk menyesatkan musuh-musuhnya dengan mengirimkan Umpan , hanya untuk keluar sambil memegang Boomerangnya di belakang mereka — bangkai mereka yang tercengang sudah tergantung di salah satu jaringnya.",
            "Apa yang ada di balik topeng Juggernaut, tidak ada yang bisa mengatakannya. Yang terakhir dari jenisnya, Yurnero membawa sendiri tradisi bela diri dari pulau asalnya, sekarang tenggelam selamanya di bawah ombak. Menari dengan Pedangnya , Juggernaut meningkatkan permainan pedang ke bentuk seni, dengan Cepat Memotong musuh dalam Fury Blade yang tak terhentikan , menyerang titik-titik yang paling rentan. Dengan keterampilan yang diasah dengan sempurna, Yurnero dapat terus menebas dan berlari di antara lawan sambil sama sekali tidak memberi mereka kesempatan untuk membalas bahkan sedikit pun. Satu-satunya pilihan mereka untuk menghindari serangan gencar ini adalah memesannya secepat mungkin. Setelah mengeluarkan isi perut musuhnya, Yurnero menempatkan Ruang Penyembuhan ponsel portabelnyayang memancarkan energi meditatif untuk merevitalisasi dirinya dan sekutu terdekat.",
            "Dipilih oleh kekuatan alam karena kebijaksanaannya yang mendalam, Sylla adalah satu-satunya yang tersisa dari klannya yang terlupakan . The Lone Druid diikuti oleh Spirit Bear -nya , pendamping kuat yang menjerat musuh, dan menghancurkan struktur. Suara Savage Roar sering kali diperlukan untuk menakut-nakuti musuh dari hutan. Jika tidak, maka pasangan ini akan mensinergikan Spirit Link , meningkatkan kecepatan dan daya tahan mereka saat mereka menjelajahi daratan untuk mencari penyusup. Manusia atau beruang, perbedaannya tidak selalu jelas. Ketika situasi mengharuskannya, Lone Druid mengambil Bentuk Sejatinya , dan bergabung dengan mêlée untuk melawan cakar-ke-cakar bersama beruangnya.",
            "Melepaskan masa lalunya yang kejam, Luna bersumpah melayani Selemene , dan menyandang gelar Moon Rider. Dewi menganugerahkan Berkah Lunar pada juara barunya, meningkatkan kekuatannya dan meningkatkan indra nokturnalnya. Dibebani di atas Nova , tunggangannya yang mengerikan, Luna melintasi Hutan Nightsilver untuk menghajar para penyusup dengan Lucent Beam yang membakar . Angka superior bukanlah keuntungan melawan Penunggang Bulan. Melalui kehendak ilahi, matahari tengah hari memberi jalan kepada malam, dan setiap musuh terkena sinar energi bulan saat Luna merobek barisan mereka dengan Moon Glaives yang terbang . Dengan kemarahan Selemene atau melalui tangannya sendiri, Penunggang Bulan meratakan medan perang di bawah kegelapan singkat gerhana.",
            "Serangan konstan adalah kunci keberhasilan Medusa. Terbungkus dalam Mana Shield , dia bertahan bahkan dari kemungkinan yang paling tidak menguntungkan. Musuh yang digigit oleh Mystic Snake mengisinya dengan energi, sumber daya yang kembali ke Medusa untuk penggunaan defensifnya. Dia Membagi Tembakannya untuk merobohkan gelombang musuh. Pahlawan yang melihatnya mungkin sulit untuk berpaling. Ketakutan, tidak ada yang bisa berharap untuk mendekati Medusa Berdarah Dingin sebelum Stone Gaze legendaris Gorgon mengubah tubuh mereka menjadi patung.",
            "Terbagi Mereka Berdiri , bersatu mereka jatuh, di mana ada satu Meepo, berharap untuk melihat lebih banyak saat mereka Poof terhadap satu sama lain untuk bantuan. Menyebarkan klonnya di seluruh medan perang, The Meepos Mengikat musuh mereka ke bumi, menghancurkan mereka dengan sekop mereka ke tanah, Menghancurkan vitalitas mereka untuk diri mereka sendiri. Meskipun Meepo yang menggunakan sekop relatif tidak berbahaya dan mungkin Menggali ke dalam tanah untuk keselamatan mereka sendiri, segerombolan Meepo yang marah dapat membanjiri bahkan pahlawan yang paling kuat sekalipun.",
            "Mirana berpatroli di Hutan Nightsilver , selalu waspada terhadap mereka yang berani mengambil dari cagar Dewinya. Melompat beraksi di atas kucing putihnya , Sagan , Putri Bulan memanggil Starstorm surgawi untuk menghujani gelombang meteor pada musuh di sekitarnya. Memegang busur berujung dengan bijih bulan, dia membidik dengan terampil dengan Panah Suci untuk menemukan tandanya dari jarak yang ekstrim. Dengan restu dari Selemene , Mirana menyelimuti tanah di Moonlight Shadow , melindungi sekutunya dari mata musuhnya, dia memastikan bahwa timnya selalu berkeliaran.",
            "Selalu mencari pertarungan yang bagus, Raja Kera Menari dan melakukan perjalanan di atas pohon yang bertujuan untuk melompat dari naungan rimbun dan mengejutkan musuh-musuhnya. Sejumput rambut—dicabut dari kepalanya—berhamburan ke angin, memanggil dan memerintahkan pasukan Tentara Monyet untuk mengalahkan lawan, Trickster yang gesit ini bersenang-senang dalam kekacauan pertempuran, siap menunjukkan Penguasaan atas seninya, membanting legendanya Staf Tanpa Batas di bawah harapan untuk melarikan diri.",
            "Setelah ribuan tahun perjalanan dalam kegelapan ruang angkasa, komet es itu jatuh ke bumi, dan dari sana muncul suatu makhluk unsur cairan hidup. Tidak terikat oleh bentuk permanen apa pun, Morphling Mengubah Atribut untuk mencocokkan kebutuhannya dan Morph menjadi replikasi musuhnya, meniru kemampuan mereka, membuat mereka bertarung melawan salinan diri mereka sendiri. Bergeser antara penyerang yang kuat, dan penyintas yang tangguh, Morphling bisa sama sulitnya dengan dia mematikan. Dengan asumsi bentuk Gelombang untuk mengapit musuh, ia melonjak ke depan sebelum melakukan Serangan Adaptif air yang menyengat atau memukul korban tergantung pada komposisinya.",
            "Pernah menjadi komandan Pengawal Slithereen yang sangat dihormati , Slithice jatuh dari kehormatan setelah pengawasan yang tampaknya sepele. Dia harus menemukan satu piala yang dicuri, atau tetap dibuang selamanya. Slithice membagi pasukan Gambar Cermin , mengirim mereka untuk mengintai ke depan dan menyesatkan musuh. Dia menjerat target dalam jaring bercahaya, lalu menyerang dengan Rip Tides untuk melunakkan armor mereka. Dengan suaranya, musuh berhenti di tengah ayunan, menurunkan senjata mereka pada suara aria yang menghantui. Di sana mereka akan berdiri, terpesona, tidak responsif terhadap sekutu Slithice yang mengepung saat mereka mendengarkan Lagu Siren yang telah membuai mereka sampai mati.",
            "Di dalam koloni scarabs fanatik, dewi ratu Nyx memilih satu grub untuk menjawab panggilan tertingginya. Maka, melalui metamorfosis yang dirancang, Nyx Assassin muncul. Scarab telepati Melahap dan Membakar pikiran mangsanya, sambil mengirimkan deretan paku bawah tanah untuk Menusuk mereka dari bawah. Dipersenjatai dengan Carapace Mencerminkan , dia membuat stun penyerang dan membalikkan serangan balik apa pun. Mengorbankan mobilitas dengan Burrowingke dalam tanah, Nyx Assassin menghilangkan sensor yang tidak perlu, meningkatkan kekuatan regeneratif dan ketahanannya sambil sangat meningkatkan jangkauan kekuatan lainnya. Tapi pelayan dewi paling mematikan saat tidak terlihat. Target yang terganggu tidak memiliki kesempatan untuk bereaksi saat Nyx Assassin menusuk tubuhnya dengan rahang besar, sehingga memenuhi Vendetta yang tak terucapkan atas nama ratunya.",
            "Menyukai anggur, wanita, dan ingin berlari ke dalam bahaya pada saat itu juga, Pangolier dapat Swashbuckle dan menahan miliknya. Dia berkembang dengan mengganggu gerakan musuh dan menempatkan dirinya di tengah-tengah kekacauan. Dengan cerdik membimbing rapiernya di antara celah-celah baju besi saat ia menangkis serangan dengan Sisik Pelindungnya , pendekar pedang yang anggun ini selalu siap untuk Berguling ke medan perang, Bergemuruh seperti Batu dan membanting musuh ke samping, membuka jalan menuju kemenangan. Selain menyerang, Pangolier dapat melakukan segala tindakan tanpa harus menghadap ke sasarannya.",
            "Dari semua pembunuh yang dibesarkan oleh Sisters of the Veil , hanya satu yang diketahui namanya: Mortred. Melalui meditasi dan ramalan, perintah mengidentifikasi target berikutnya untuk mati di tangannya. Serangan meleset ke Phantom Assassin saat dia Mengaburkan ke sekelilingnya, melintasi tanah tanpa terdeteksi untuk menangkap korbannya tanpa disadari. Dia membuka pertemuan dengan Belati yang Menyesakkan , dilempar dari bayang-bayang, lalu melompat ke atas target yang lumpuh untuk memberikan serangan Phantom Strikes , diikuti oleh Kipas Pisau yang dilemparkan ke segala arah. Tanpa peringatan, salah satu dari serangannya bisa menjadi Coup de Rahmat , hanya menyisakan tanah berlumuran darah sebagai bukti efisiensinya.",
            "Saat Azwraith mengarahkan tombaknya melalui Vorn , Dread Magus hancur menjadi pecahan cahaya yang tak terhitung banyaknya, memenuhi pembunuhnya dengan kekuatan baru yang aneh. Dulunya adalah seorang nelayan yang rendah hati, Phantom Lancer Spears menargetkan dari jauh, menelurkan fragmen Phantom Lancer sendiri saat mereka berlari ke depan sambil memotong musuh dalam serangkaian serangan yang menakjubkan. Ketika terpojok, dia menghilang sebentar dari medan perang, muncul kembali di tempat terdekat sambil meninggalkan Doppelganger untuk menyesatkan dan menghindari pengejar. Banyaknya pasukannya sering disandingkan dengan musuh-musuhnya, membanjiri mereka di depan mata mereka hampir tidak dapat membedakan Phantom Lancer dari pasukan kloningnya.",
            "Cambuk yang mengantar orang mati melalui Narrow Maze membawa banyak rasa sakit di medan perang. Razor menyebarkan cincin luas Lapangan Plasma untuk menggoreng musuh-musuhnya, dia Menghubungkan musuh-musuhnya untuk menguras kekuatan mereka dan menggunakannya untuk melawan mereka. Lightning Revenant disertai dengan Gelombang Badai yang luar biasa . Dengan badai petir yang mematikan atas perintahnya, sering kali musuh-musuhnya menemukan diri mereka terjerat dalam Mata Badai bahkan sebelum menyadarinya, saat Razor menyaksikan dan menikmati pekerjaannya saat sambaran petir mengurangi musuhnya menjadi sisa-sisa hangus.",
            "Meninggalkan kehidupan masa lalunya, Riki melarikan diri dari tanah kerajaan menggunakan metode Jubah-dan-Belatinya sendiri . Diam dan suka membunuh dari belakang, Riki melempar Smoke Screen yang tebal , membutakan dan mencekik musuh saat dia mengejutkan mereka dengan Blink Strike . Penyusup yang memasuki wilayahnya disambut dengan belati kembar, kilatan baja yang menebas secara bersamaan di setiap belokan, atau ditenangkan oleh Sleeping Dart khasnya , sementara tuannya sendiri tetap tidak terlihat. Bagaimana prestasi ini dicapai tetap menjadi misteri, karena Pembunuh Siluman bukanlah orang yang membocorkan Trik Perdagangannya .",
            "Menangkap Jiwa dari setiap pembunuhan yang dia lakukan, Shadow Fiend selalu mengumpulkan kekuatannya. Armor gagal dalam Kehadiran Pangeran Kegelapan , membuat musuh tidak punya pilihan selain berebut. Setiap serangan, setiap Shadowraze yang diarahkan dengan hati-hati membunuh musuh, membawanya lebih dekat ke puncak potensinya. Shadow Fiend berhenti sejenak untuk mengisi energi iblisnya, kemudian, dengan kepakan sayapnya yang tidak ringan, melepaskan jiwanya yang terkumpul ke segala arah untuk melenyapkan musuh dalam Requiem of Souls yang melolong .",
            "Satu-satunya tahanan yang pernah melarikan diri dari Dark Reef , kemampuan dan kekejaman Slark tidak ada bandingannya. Menerkam ke dalam bahaya lalu menyelinap keluar adalah hal terbaik yang dilakukan Slark. Dengan setiap ayunan belati bertatahkan teritip, Slark mencuri Essence targetnya , mengubahnya menjadi lebih gesit, menyerang lebih keras dan lebih cepat. Dia menempa Pakta Gelap , mengorbankan darah hidupnya sendiri untuk menghilangkan energi negatif yang merusak musuh, dan membebaskannya dari kendala magis. Menyembunyikan dirinya saat dia Menari melalui Bayangan , Nightcrawler tidak memberikan target yang terlihat kepada calon penyerang. Tersembunyi dan Terselubungdalam kabut hitam ini, Slark lolos dari yang tak terhindarkan dan selalu siap untuk memusnahkan musuh-musuhnya dengan sedikit risiko pembalasan.",
            "Dengan satu peluru, Kardel Sharpeye menembus mata tengah penguntit curam dari dasar lembah, tindakan tidak menyenangkan yang mengakibatkan pengasingan ritualnya. Dia akan memenangkan pujian di medan pertempuran, atau tidak pernah kembali. Seperti kerabat gunungnya, Penembak Jitu adalah satu dengan senjata apinya. Dia Membidik dari jarak yang sangat jauh, dan mencetak Headshots yang menghentikan targetnya mati. Berbekal senapan modular, Kardel meluncurkan peluru pembakar untuk menghujani pecahan peluru atau melempar granat yang menjatuhkan musuhnya ke posisi yang sudah mapan. Tidak ada musuh yang aman dalam jangkauan Penembak Jitu. Saat dia berhenti untuk mengatur garis bidiknya, mengkompensasi setiap variabel sebelum dia membunuh tandanya dalam satu tembakan fatal.",
            "Makhluk abadi dari energi kekerasan, Mercurial, Spectre sangat tertarik pada konflik. Melemparkan Spectral Dagger , menciptakan jejak bayangan ke musuhnya di mana dia dapat melakukan perjalanan tanpa halangan. Kerusakan yang dilakukan pada Mercurial sebagian dibelokkan dan Didispersikan ke musuh terdekat yang memperpanjang daya tahannya. Bahkan di hutan belantara yang paling sunyi , para pelancong dihantui oleh penampakan Spectre, seolah-olah memangsa kesendirian mereka. Tapi ini bukan ilusi belaka. Dikatakan bahwa untuk satu dari setiap lima hantu, penampakan menjadi Realitas , dan di samping para korban malang ini, Spectre Shadow Steps , membawa kehancuran dan murka yang dia dambakan selamanya.",
            "Menekuk hukum alam itu sendiri, Lanaya membentuk bidang Refraksi yang menyerap pukulan masuk, namun memperkuat serangan keluar. Dia menyatu ke latar belakang, berbaring untuk menyergap untuk melepaskan ledakan energi psionik pada target yang tidak curiga. Cahaya ungu memancar dari ujung jarinya, Psi Blades -nya mengungguli semua senjata jarak dekat, mencabik-cabik dan menembus barisan musuh sekaligus. Teguh dalam tujuannya, Lanaya menandai tanah dengan lingkaran ajaib desain eldritch. Mereka yang berjalan tanpa sadar di atas Perangkap Psionic hanya bisa tertatih-tatih menjauh dari ledakan — karena kehadiran mereka telah terungkap, dan pembunuh yang memproyeksikan dirinya ke tempatnya tidak jauh di belakang.",
            "Dinding fraktal Foulfell tidak hanya gagal menahan Terrorblade, tetapi juga memberinya kendali baru atas Refleksi bengkoknya . The Demon Marauder Conjure Gambar dirinya, membingungkan musuh dan melipatgandakan kerusakannya. Memakan amarah dan semangatnya sendiri , Terrorblade berubah menjadi bentuk yang lebih mengesankan; Metamorfosis tidak suci yang memungkinkan dia untuk melemparkan energi iblis dari jarak jauh dan mengirimkan Gelombang Teror yang mengguncang musuh-musuhnya. Musuh yang berpengalaman tahu bahwa iblis yang terluka masih jauh dari kalah. Di ambang kematian, Terrorblade memberi tip pada timbangan, menghilangkan kebutuhan untuk mundur saat dia menukar kesehatannya yang terkuras dengan kesehatan lawannya, Sundering .hati mereka oleh rasa takut.",
            "Jah'rakal adalah bajingan yang tak tertahankan, bahkan untuk seorang troll. Karena itu, ditendang keluar dari perkemahan troll hanya memicu kemarahannya. Keesokan harinya, dia kembali dengan kapak di tangan, dan membunuh mantan rekannya dalam Kemarahan Berserker . Dengan setiap pukulan yang lewat, Troll Warlord gadungan mempercepat ayunannya dalam Semangat yang marah . Langsung dapat bertukar antara serangan jarak dekat dan jarak jauh, dia melemparkan Kapak Berputarnya untuk melumpuhkan dari jauh, sambil menebas musuh yang berdekatan. Menantang Jah'rakal berarti mengundang kematian sendiri. Troll Warlord memasuki Battle Trance , menyalurkan kebencian murni ke dalam kecepatan yang tiada bandingnya saat dia mengamuk ke depan, menghancurkan lawan-lawannya dalam badai kapak berdarah.",
            "Anggota paling ganas dari suku ursine-nya, Ulfsaar menjadikannya tujuannya untuk mencari pemicu kejahatan di luar tanah airnya. Prajurit Ursa melompat dan Mengguncang Tanah , memperlambat musuh saat dia mengalahkan mereka dengan serangan tanpa henti. Cakarnya menggali untuk memperlebar luka, menimbulkan kerusakan yang lebih besar dengan setiap Gesek Fury berturut-turut . Ursine yang marah adalah pemandangan yang harus dilihat. Mengabaikan semua rasa sakit, Prajurit Ursa masuk ke kegilaan yang benar, dan menekan lawannya untuk menganiaya mereka tanpa bisa dikenali.",
            "Dirampas sayapnya dan tempat yang seharusnya di Ghastly Eyrie , Shendelzare memohon kepada dewi Scree'auk untuk memberinya energi gelap yang akan menyelesaikan pembalasannya. Dengan Gelombang Teror , sang putri yang jatuh mengumumkan kedatangannya, musuh yang menakutkan cukup dekat untuk mendengar tangisannya yang sedih. Seperti saudara-saudaranya di udara, Vengeful Spirit menggunakan Magic Missle secara bebas, mantra Skywrath sederhana untuk musuh yang menakjubkan. Mencari kemartiran, Shendelzare langsung Menggantikan dirinya dengan target yang dia pilih, dengan senang hati mengorbankan dirinya saat dia bertukar posisi dengan sekutu yang terkepung, atau musuh yang melarikan diri. Yang layak yang bertarung bersama Shendelzare dikuatkan olehnyaVengeance , fanatisme yang mengintensifkan pukulan mereka dan bertahan bahkan setelah kematiannya, karena kehadiran Roh Vengeful dirasakan setiap saat.",
            "Venomancer membawa kematian lambat ke musuh-musuhnya. Ia menginfeksi makhluk hidup lain dengan sentuhannya, dan memuntahkan Venomous Gales untuk memperlambat dan meracuni mangsa yang melarikan diri. Sebagian reptil dan sebagian anggrek, ia menumbuhkan pasukan penjaga peludah racun yang tak ada habisnya, Bangsal Wabah , untuk mempertahankan batasnya dengan Acid Spit . Jika musuh mendekat, mereka disemprot dengan Poison Nova yang besar dan berbahaya , memastikan bahwa bahkan mereka yang lolos akhirnya menyerah pada banyak racun Venomancer.",
            "Sungguh bodoh mencoba dan menjinakkan Netherdrake , sebuah pelajaran yang dipelajari penyihir tua itu dalam kematian. Terbebas dari penculiknya, Viper melebarkan sayapnya dan pergi menjelajahi dunia permukaan. Dengan Serangan Racun yang diresapi dengan cairan yang tidak berbahaya, menyebabkan persendian mengeras, melumpuhkan musuh apakah mereka memilih untuk melarikan diri atau bertarung. Nethertoxin menyebar ke seluruh tubuh mereka, mengubah luka menjadi kematian, dan kelelahan menjadi kematian. Netherdrake yang tangguh, Kulit Korosif melindungi dari keterampilan mantra, dan membakar penyerang dengan asam. Tapi itu adalah Serangan Viper yang ditakutiyang menandakan awal dari akhir. Korban yang menderita terhuyung-huyung merangkak, nyaris tidak bisa mengambil langkah berikutnya. Jika Netherdrake tidak menghabisi targetnya, racun di pembuluh darah mereka akan.",
            "Semua Penenun bekerja untuk mempertahankan kain ciptaan, kecuali satu Skitskurr, yang mengambilnya sendiri untuk menciptakan apa yang belum ditenun. Diusir karena ambisinya, Skitskurr sekarang bebas dari kewajibannya, bebas menenun realitas barunya sendiri. Membuka celah dalam ruang-waktu, Weaver mengundang \" The Swarm \" — Weaver muda untuk menyerang musuh, dan menggigit armor mereka. Hampir tidak mungkin untuk dijabarkan, dia menyelinap ke lubang cacing mikro, melewati musuh dan muncul kembali dengan Shukuchi . Alur waktu berkecamuk di sekitar Skitskurr, kadang-kadang diputar ulang, menyebabkan Serangan Geminate -nyauntuk disaksikan — dan dirasakan — lebih dari sekali. The Weaver mengambil brinkmanship ke ekstrim. Berjuang di ambang kematian, Skitskurr memutar balik waktu dengan Time Lapse , membalikkan luka-lukanya dan membatalkan upaya musuhnya, yang membuat mereka kecewa."
    };

    private static int[] contentsImages = {
            R.drawable.antimage,
            R.drawable.arcwarden,
            R.drawable.bloodseeker,
            R.drawable.bountyhunter,
            R.drawable.broodmother,
            R.drawable.clinkz,
            R.drawable.drowranger,
            R.drawable.emberspirit,
            R.drawable.facelessvoid,
            R.drawable.gyrocopter,
            R.drawable.hoodwink,
            R.drawable.juggernaut,
            R.drawable.lonedruid,
            R.drawable.luna,
            R.drawable.medusa,
            R.drawable.meepo,
            R.drawable.mirana,
            R.drawable.monkeyking,
            R.drawable.morphling,
            R.drawable.nagasiren,
            R.drawable.nyxassassin,
            R.drawable.pangolier,
            R.drawable.phantomassassin,
            R.drawable.phantomlancer,
            R.drawable.razor,
            R.drawable.riki,
            R.drawable.shadowfiend,
            R.drawable.slark,
            R.drawable.sniper,
            R.drawable.spectre,
            R.drawable.templarassassin,
            R.drawable.terrorblade,
            R.drawable.trollwarlord,
            R.drawable.ursa,
            R.drawable.vengefulspirit,
            R.drawable.venomancer,
            R.drawable.viper,
            R.drawable.weaver
    };

    static ArrayList<Content> getListData() {
        ArrayList<Content> list = new ArrayList<>();
        for (int position = 0; position < contentsName.length; position++) {
            Content content = new Content();
            content.setName(contentsName[position]);
            content.setType(contentType[position]);
            content.setComplexity(contentComplexity[position]);
            content.setDetail(contentDetails[position]);
            content.setPhoto(contentsImages[position]);
            list.add(content);
        }
        return list;
    }
}
